[build]
builder = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile"

[deploy]
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services]
[services.app]
name = "digital-literacy-backend"
port = 8000
command = "poetry run uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[services.db]
name = "digital-literacy-db"
type = "postgresql"
plan = "hobby" 