"""Modify exam schema again

Revision ID: 264e1360047b
Revises: 61494e2bd473
Create Date: 2025-04-10 12:26:12.932086+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264e1360047b'
down_revision: Union[str, None] = '61494e2bd473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_attempts_candidate_id_fkey', 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attempts', 'candidates', ['candidate_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.create_foreign_key('exam_attempts_candidate_id_fkey', 'exam_attempts', 'users', ['candidate_id'], ['id'])
    # ### end Alembic commands ### 